version: '3'
services:
  db-postgres:
    restart: always
    image: "postgres:13.0-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mpeix
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ../postgres/mpeix:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

volumes:
  database-data:
